matrix:
  include:
    - os: osx
      osx_image: xcode9.4
      language: node_js
      node_js: "12"

    - os: linux
      services: docker
      language: node_js
      node_js: "12"

cache:
  directories:
    - node_modules
    - $HOME/.cache/electron
    - $HOME/.cache/electron-builder

script:
  - yarn release

branches:
  only:
    - master